version: '3.8'

services:
  parser:
    build: .
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=db
      - DB_PORT=5432
      - CHAINABUSE_API_TOKEN=${CHAINABUSE_API_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - LOG_FILE=${LOG_FILE:-parser.log}
      - CLEAR_EXISTING_DATA=${CLEAR_EXISTING_DATA:-false}
    depends_on:
      - db
    volumes:
      - app_data:/app/data

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"

volumes:
  postgres_data:
  app_data: 